import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { Menu, MenuButton, MenuItem, MenuItems } from '@headlessui/react';
import { ChevronDownIcon } from '@heroicons/react/20/solid';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Solutions() {
  return (
    <Menu as="div" className="relative inline-block">
      <MenuButton className="inline-flex w-full justify-center gap-x-1.5 rounded-md border border-white/20 bg-black/70 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-white/10">
        Solutions
        <ChevronDownIcon aria-hidden="true" className="-mr-1 size-5 text-gray-400" />
      </MenuButton>

      <MenuItems
        transition
        className="absolute right-0 z-10 mt-2 w-56 origin-top-right rounded-md border border-white/10 bg-black/90 text-white shadow-lg outline-none transition data-closed:scale-95 data-closed:transform data-closed:opacity-0 data-enter:duration-100 data-enter:ease-out data-leave:duration-75 data-leave:ease-in"
      >
        <div className="py-1">
          <MenuItem>
            <a
              href="/twitter"
              className="block px-4 py-2 text-sm text-gray-200 data-focus:bg-white/10 data-focus:text-white data-focus:outline-hidden"
            >
              Twitter
            </a>
          </MenuItem>
          <MenuItem>
            <a
              href="/predictions"
              className="block px-4 py-2 text-sm text-gray-200 data-focus:bg-white/10 data-focus:text-white data-focus:outline-hidden"
            >
              Predictions
            </a>
          </MenuItem>
        </div>
      </MenuItems>
    </Menu>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 w-full bg-black">
          <nav className="relative mx-auto flex h-14 max-w-6xl items-center justify-center px-4 text-sm text-white">
            <div className="flex items-center gap-8">
              <Link href="/" className="hover:text-gray-300">Home</Link>
              <Link href="/careers" className="hover:text-gray-300">Careers</Link>
              <Link href="/about" className="hover:text-gray-300">About</Link>
              <Solutions />
            </div>
            <Link href="/login" className="absolute right-4 rounded-md border border-white/20 px-4 py-1.5 hover:bg-white/10">Login</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
